#!/bin/sh
#
#  compile_bm+_files: Byte-compile Bookmark+ elisp files.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

rm *.elc

# Note: Compile and load bookmark+-mac.el first.
emacs -q -batch -L . \
-f batch-byte-compile \
bookmark+-mac.el

emacs -q -batch -L . \
-l bookmark+-mac.elc \
-l bookmark+.el \
-l bookmark+-1.el \
-l bookmark+-bmu.el \
-l bookmark+-key.el \
-l bookmark+-lit.el \
 \
-f batch-byte-compile \
bookmark+.el \
bookmark+-1.el \
bookmark+-bmu.el \
bookmark+-key.el \
bookmark+-lit.el \
