#!/bin/sh
#
#  get_bm+_files: Retrieve current source for Emacs bookmark+ from EmacsWiki
#
#  This is the canonical source for bookmark+.  It seems to exist on GitHub
#  only as a repo of thousands of mirrored files.
#

# Get EmacsWiki documentation for Bookmark+.
wget -O BookmarkPlus.html https://www.emacswiki.org/emacs/BookmarkPlus

# Get Bookmark+ source.
wget https://www.emacswiki.org/emacs/download/bookmark+.el
wget https://www.emacswiki.org/emacs/download/bookmark+-1.el
wget https://www.emacswiki.org/emacs/download/bookmark+-bmu.el
wget https://www.emacswiki.org/emacs/download/bookmark+-chg.el
wget https://www.emacswiki.org/emacs/download/bookmark+-doc.el
wget https://www.emacswiki.org/emacs/download/bookmark+-key.el
wget https://www.emacswiki.org/emacs/download/bookmark+-lit.el
wget https://www.emacswiki.org/emacs/download/bookmark+-mac.el

date -u > date_retrieved
