#+TITLE: Bookmark+ Package for Emacs
#+STARTUP: align
#+STARTUP: content
#+STARTUP: inlineimages


* License Notice

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

* About this Repository

This is my collection of Drew Adams' *Bookmark+* elisp files.  Their
canonical respository is on [[https://www.emacswiki.org/emacs/BookmarkPlus][EmacsWiki]], from whence they are downloaded
by my ~get_bm+_files~ script.  There doesn't seem to be any more
convenient way of obtaining them -- so this is what I've come up with.
(There is a copy on GitHub under the ~emacsmirror/emacswiki.org~ repo,
but that seems to contain thousands of files in its top-level
directory and, as such, is impractical to use.)

On MacOS, I currently run Emacs 26.1 from https://emacsformacosx.com.
Byte compilation produces some warnings (mostly for obsolete
functions), but the package seems to run properly.  This is the
environment I use to run the included shell scripts.

I've yet to investigate the "optional crosshairs feature" mentioned on
EmacsWiki.  In the future, I may include ~crosshairs.el~, /etc./, in
this repository.

* Updates

The contents of this repository may be updated with Drew Adams'
latest, canonical Bookmark+ source by executing my ~get_bm+_files~
shell script.

* Installation

The files can be byte-compiled by running the included
~compile_bm+_files~ script.

Something like the following should be in ones Emacs init file:

: (add-to-list 'load-path "~/path/to/bookmark_plus")
: (require 'bookmark+)

* Documentation

The file ~bookmark+-doc.el~ is Drew Adams' official Bookmark+
documentation, and the file ~bookmark+-chg.el~ is the official change
log.  (I'm not sure why they're ~.el~ files, /but..../)  My
~get_bm+_files~ script also retrieves the EmacsWiki page for the
package as ~BookmarkPlus.html~, which is similar in content to
~bookmark+-doc.el~, but includes comments.

* License

Everything here is Free Software.  As Drew Adams' files contain GPLv3+
license notices, I am following suit on my humble additions.

